IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'FI_SP_PesqBeneficiarios')
BEGIN
    DROP PROC FI_SP_PesqBeneficiarios
END
GO

CREATE PROCEDURE FI_SP_PesqBeneficiarios
    @IDCLIENTE BIGINT
AS
BEGIN
    SELECT ID, NOME, CPF, IDCLIENTE FROM BENEFICIARIOS WHERE IDCLIENTE = @IDCLIENTE
END
GO