IF EXISTS (SELECT * FROM sys.objects WHERE type = 'P' AND name = 'FI_SP_ConsCliente')
BEGIN
    DROP PROC FI_SP_ConsCliente
END
GO

CREATE PROC FI_SP_ConsCliente
    @ID BIGINT
AS
BEGIN
    IF(ISNULL(@ID, 0) = 0)
        SELECT NOME, SOBRENOME, NACIONALIDADE, CEP, ESTADO, CIDADE, LOGRADOURO, EMAIL, TELEFONE, CPF, ID 
        FROM CLIENTES WITH(NOLOCK)
    ELSE
        SELECT NOME, SOBRENOME, NACIONALIDADE, CEP, ESTADO, CIDADE, LOGRADOURO, EMAIL, TELEFONE, CPF, ID 
        FROM CLIENTES WITH(NOLOCK) 
        WHERE ID = @ID
END
GO